export const APP_NAME = "TelegramHub"
export const APP_TAGLINE = "我的TG个人云盘"
export const APP_CATEGORY = "TG Cloud Drive"
export const APP_DESC_EN = "A Serverless Personal Cloud Drive"
export const APP_DESC_CN = "基于 Cloudflare KV + Telegram Bot API 的免费私人云盘"
